version: '3'
services:
  wazuh:
    build: wazuh
    hostname: wazuh-manager
    container_name: wazuh
    restart: always
    environment:
      - SSL_CERTIFICATE_AUTHORITIES=/etc/filebeat/CA.PEM
      - SSL_CERTIFICATE=/etc/filebeat/node.pem
      - SSL_KEY=/etc/filebeat/key.pem
      - USERNAME=usertest
      - PASSWORD=passwordtest
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    networks:
      - odfe-net

volumes:
  odfe-data1:

networks:
  odfe-net:
