version: '2'
services:
  wazuh:
    build: wazuh
    hostname: wazuh
    container_name: wazuh
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    volumes:
      - ./root-ca.pem:/etc/filebeat/root-ca.pem
    environment:
      - ELASTICSEARCH_URL=https://elasticsearch:9200
      - SSL_CERTIFICATE_AUTHORITIES=/etc/filebeat/root-ca.pem
      - USERNAME=admin
      - PASSWORD=admin
    networks:
      - odfe-net

  elasticsearch:
    image: amazon/opendistro-for-elasticsearch:1.1.0
    hostname: elasticsearch
    container_name: elasticsearch
    environment:
      - cluster.name=odfe-cluster
      - node.name=odfe-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - ./custom-elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
      - ./node.pem:/usr/share/elasticsearch/config/node.pem
      - ./node-key.pem:/usr/share/elasticsearch/config/node-key.pem
      - ./admin.pem:/usr/share/elasticsearch/config/admin.pem
      - ./admin-key.pem:/usr/share/elasticsearch/config/admin-key.pem
     
    networks:
      - odfe-net
     
  kibana:
    build: kibana
    hostname: kibana
    container_name: kibana
    ports:
      - "5601:5601"
    expose:
      - "5601"
    volumes:
     - ./custom-kibana.yml:/usr/share/kibana/config/kibana.yml
     - ./root-ca.pem:/usr/share/kibana/config/root-ca.pem
     - ./node.pem:/usr/share/kibana/config/node.pem
     - ./node-key.pem:/usr/share/kibana/config/node-key.pem
    environment:
      CURL_PARAMETERS: "--cacert /usr/share/kibana/config/root-ca.pem -u admin:admin -k"
      ELASTICSEARCH_URL: "https://elasticsearch:9200"
    networks:
      - odfe-net

volumes:
  odfe-data1:
  odfe-data2:

networks:
  odfe-net: