version: '3'
services:
  wazuh:
    image: wazuh/wazuh:3.9.4_7.1.1-opendistro-security
    hostname: wazuh-manager
    container_name: wazuh
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    # environment:
    #   - SSL_CERTIFICATE_AUTHORITIES=/etc/filebeat/CA.PEM
    #   - SSL_CERTIFICATE=/etc/filebeat/node.pem
    #   - SSL_KEY=/etc/filebeat/key.pem
    #   - USERNAME=usertest
    #   - PASSWORD=passwordtest

  elasticsearch:
    image: wazuh/wazuh-elasticsearch:3.9.4_7.1.1-opendistro
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_CLUSTER=true
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g

  kibana:
    image: wazuh/wazuh-kibana:3.9.4_7.1.1-opendistro
    hostname: kibana
    restart: always
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh
