name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1

      - name: Login to github registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKER_REGISTRY_URL: docker.pkg.github.com

      - name: Build :latest
        if: success()
        run: docker build wazuh/ -t docker.pkg.github.com/manuasir/wazuh:nightly .
        
      - name: Push to docker hub :nightly
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push docker.pkg.github.com/manuasir/wazuh:nightly