name: Wazuh Docker pipeline

on: [push, pull_request]

jobs:
  build-stack:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build the docker-compose stack
      run: docker-compose up -d --build
    - name: Check running containers
      run: docker ps -a
